---
title: "ECON 529 - Research Methods I: Econometrics"
format:
  html:
    css: styles.css
  pdf: default
---

**Instructor:** Fernando Rios-Avila  
**Office:** Room 307, Blithewood  
**Office Hours:** Friday, 9:00 am to 10:00 am or by appointment  
**Phone:** 845-758-7719  
**Email:** friosavi@levy.org  
**Time and Location:** Wednesday, 9:30 am to 12:50 pm  

## Course Description

The course aims to provide students with a foundation in applied econometrics that is required for the successful completion of the program. The emphasis of the course is on understanding the intuition behind model estimation, hypothesis testing, and economic interpretation of statistical results.

We begin by discussing the nature of econometrics and economic data. This is followed by a discussion of estimation and inference in univariate and multivariate regression models of cross-sectional data. We will review some of the consequences of heteroscedasticity, measurement errors, and endogeneity, among other issues of model specification and data measures. The second part of the course will cover advanced regression models such as limited dependent variables, panel data, and time series data.

The class is taught through a combination of lectures, discussion, homework, quizzes, and exams. Student involvement and participation in class are highly encouraged.

## Required Text

Introductory Econometrics: A Modern Approach

by Jeffrey M. Wooldridge

- While any edition will do, exercises and exam material will be taken from the 7th edition.

**Suggested:**

Using R for Introductory Econometrics (recommended)

by Florian Heiss

- This book introduces the free programming language and software package R with a focus on the implementation of standard tools and methods used in econometrics. It builds on the textbook "Introductory Econometrics: A Modern Approach" by Jeffrey M. Wooldridge. The book can be accessed online [here](https://www.urfie.net/).

  The author also provides textbooks using the same structure, introducing `Julia` and `python`.

## Course website

We will be using `Github` pages to provide all lectures and homework. It is your responsibility to access the site or communicate with me if any questions should arise.

This is where assignments, readings, and other information will be posted.

## Grading

Grading will be based on homework assignments, quizzes, and exams. Their grade distribution is as follows:

* **Homework (55%)**: Three homework assignments will be given throughout the semester. Homework assignments are prepared for you to implement the methodologies covered in class, as well as encourage you to interpret the results. Each homework will consist of a small research project where you will be asked to answer a series of questions, as if you were writing a research paper.

  The homework assignments will require using data and the statistical software `Stata`. You are free to use any of the data sets that come along with the textbook. They can be accessed using `frause` in `Stata`. It is encouraged that homework assignments are prepared and submitted in pairs.

  All homework assignments will be posted on the course website. When submitting your homework, prepare a `pdf`, `html`, or `doc` file with your answers, and a `do` file with the code used to answer the questions. It is highly encouraged that you use `markdown` or `quarto` to prepare your homework, as it easily allows you to incorporate all necessary information to reproduce your results.

* **Midterm and Final (40%)**: Two exams will be given. Each one is prepared to test you on concepts, interpretation, and intuition behind the econometric topics reviewed in class. The exams will be open book and open notes. You are allowed to use any printed material, including the textbook, your notes, and any other material you may find useful. You are not allowed to use any electronic devices, including computers, tablets, or phones, except for the use of a calculator.

  Questions for the midterm and final will include three sections:
    - Multiple-choice questions and concept questions.
    - Analytical section, equation solving, and derivations.
    - Empirical section, where you will be asked to interpret results from a regression analysis, as well as implement statistical tests.

  Analytical and empirical sections will be taken from the problem sets and computational exercises in the textbook.

* **Quizzes (5%)**: After each topic, there will be multiple-choice quizzes to test your knowledge of important concepts and ideas seen in class. There will also be open-ended questions or extra projects that will be provided during the semester. This includes 5 extra credit points.

* **Class Participation**: Class participation is highly encouraged. You are to participate in class discussions. You are also encouraged to ask questions and provide answers to questions asked in class. This counts for up to 5% of extra credit for your final grade.

## Attendance:

Class attendance, in-person or online, is highly recommended. Classes will not be recorded, but for exceptional cases, a link will be provided to attend the class online. Material for exams and homework will come from both class lectures as well as the book.

The only acceptable excuses for missing a test are medical reasons or family emergencies. If you have a legitimate excuse, a make-up exam will be issued soon after the date of the original exam. Any issues should be discussed with me before the actual exam takes place.

## Course Software

There are several statistical packages for analyzing data. In this course, we will be using the software `Stata` to cover all materials in class. Slides are self-replicable, thus you can copy and paste almost all code provided to replicate the results seen in class. The Institute will be providing you with licenses for Stata/BE for the length of the course.

`Stata` offers many free short webinars and video tutorials that may be useful if you never used Stata before, or even if you have some experience with it. Please see the [resources page](../resources.qmd) for more information.

If you decide to, you can use `R`, `Julia`, or `Python` to study and work on the course materials and homework. One of the recommended books has nice introductions and code that can help you get started with these software packages. The [resources page](../resources.qmd) has additional information on how to get started with these software packages.

As with many other skills, the best way to learn is to simply work with the packages, work on the book exercises, and ask any questions to me or your classmates when you find a problem you could not find a solution for.

## Additional Information:

All students are responsible for knowing Bard’s Policy on Academic Honesty as published in Bard College Student Handbook.