project:
  type: website
  output-dir: docs

execute:
  freeze: true
  cache: true

website:
  title: "Econometrics MSC Levy"
  navbar:
    left:        
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: "Resources"  
      - about.qmd
  sidebar: 
    style: docked
    search: true
    contents:
      - section: "Courses"
        contents: 
          - adv_class/index.qmd
          - rmethods/index.qmd
          - rmethods2/index.qmd
          - rm-data/index.qmd
      - section: "Math Refresher"
        contents:
          - mathref/math_1.qmd
          - mathref/math_2.qmd
          - mathref/math_3.qmd

format:
  html:
    theme:
      light: materia, prof.scss
      dark: darkly
    css: styles.css
    toc: true
 


