{
  "hash": "e3df06e87303ee680db859263dfe37d2",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Research Methods II\"\nsubtitle: \"Session 1: Surveys, IO and SAM\"\nauthor: Fernando Rios-Avila\nformat: \n  revealjs: \n    slide-number: true\n    width: 1600\n    height: 900\n    code-fold: true\n    echo: true\n    css: styles.css \n  pdf: default  \n---\n\n## Why are we here?\n\n-   If you are reading this, you are probably interested in the Microeconometrics path of Research methods II.\n\n-   This course assumes you are familiar with the basics of econometrics and statistics.\n\n    -   We will not cover questions from Research methods I. You probably know the answers to those questions already!\n\n-   This course will focus on tools that are commonly used in empirical research in economics:\n\n    -   We will emphasize the use of Household Surveys (with the issues it entails)\n\n    -   And focus on applied econometrics using cross-sectional data, for distributional analysis and policy simulation.\n\n-   Thus, we will do much more use of empirical tools and software than we did in Research methods I.\n\n-   We will have 7 Sessions, 2 homeworks and a final project.\n\n# Surveys: What are they?\n\n## What is a Survey?\n\n-   A Survey is a source of data that aims to collect information from a population of interest, to underestand some characteristics, behaviors, or opinions of that population as a whole.\n    -   The population of interest can be individuals, households, firms, etc.\n-   They can be useful to identify and analyze policy questions.\n-   However, they are secondary data, and thus have limitations in terms of the questions that can be answered with them.\n    -   You cannot answer questions that require data that was not collected.\n    -   They can also be limited to Interivewee recall, or willingness to answer.\n    -   Or how accessible the population of interest is.\n\n## Example of Surveys\n\n-   Current Population Survey (CPS)\n    -   Monthly survey of 60,000 households in the US.\n-   American Community Survey (ACS)\n    -   Annual survey of 3.5 million households in the US.\n-   American Time Use Survey (ATUS)\n    -   Annual survey of 6,000 individuals in the US.\n-   Enterprise Surveys - WB (ES)\n    -   Survey of firms in developing countries. Different years of Collection\n\n## What makes a good survey?\n\n-   A Good survey is one that allows you to obtain estimates of statistics of interest for the population with \"Tolaraable\" levels of Accuracy.\n\n-   To do this, you need to have a good sampling design (representation and \"independence of the population\") and a good questionnaire design (questions that are clear and easy to answer).\n\n-   A good survey needs to be representative of the population of interest. To do this appropriately, data will be collected based on a **frame** that will be used to select the sample.\n\n## Types of Data Seletion\n\n::: panel-tabset\n## Simple\n\n-   Each observation in the \"frame\" has the same probability of being selected in the sample.\n\n-   It may be difficult to implement in practice, because of cost and logistics. (distance)\n\n-   It could also have problems of representativeness for small groups. (rare events)\n\n## Clustered\n\n-   Using some criteria, location for example, the population is divided into clusters.\n-   For the sample selection, certain clusters are selected at random, and \"some\" observations within each selected.\n-   This is more feasible in practice, because takes advantage of the \"clustering\" of the population.\n-   However, one may need to account for possible \"common shocks\" that people within the same cluster may have.\n\n## Stratified\n\n-   Some times, statistics are required to accurately represent certain groups of the population. (by region, race, income level, etc)\n-   In such cases, data can be collected in a way that ensures that the sample has enough observations for each group of interest.\n    -   It would be as collecting multiple samples, one for each group of interest.\n-   Within each Strata, it would also be possible to use a simple or clustered sampling design.\n:::\n\n## What to be aware of?\n\n-   The sampling design is important to ensure that the sample is representative of the population of interest.\n-   However, there are limitations:\n    -   Not every-one selected will respond to the survey. (Is it random? )\n    -   Rarey one assumes equal probability of selection. (Different sampling weights)\n    -   Use of Stratatification and Clustering may require special treatment.\n-   Something else: Panel data\n    -   Because of attrition, it can be difficult to analyze if representativeity is required.\n    -   However, it can be useful to analyze dynamics.\n\n## Descriptive Statistics\n\n-   Once you have your data, you can start analyzing it by simply applying your survey weights.\n\n    -   Point estimates are straightforward to obtain.\n\n-   However, when considering the estimation of precision of the estimates (Variance and Standard Errors), there are two approaches that are important to consider:\n\n-   **Finite Population Approach**:\n\n    -   Associated with data description\n    -   Assumes that the population is finite, and thus Selection probabilities are not independent.\n\n-   **Superpopulation Approach**:\n\n    -   Associated with data modeling.\n    -   Population is infinite. Selection probabilties are independent.\n\n-   For practical purposes, the difference between the two approaches is not that important.\n\n    -   With large enough samples, he \"finite sample correction\" is negligible.\n\n## Basic Summary Statistics:\n\n-   $n$ is sample size. $N$ is population size.\n-   $a_i$ an indicator of belonging to the sample. $\\sum a_i=n$\n-   Assume $y_i$ is the outcome of interest, Say income. $$\\texttt{mean: }\\hat{\\mu}_y=\\bar{y} = \\frac{1}{n}\\sum_{i=1}^N a_i y_i = \\frac{1}{n}\\sum_{j=1}^n y_j$$ $$\\texttt{Variance: }\\hat \\sigma^2_y = \\frac{1}{n-1} \\sum_{i=1}^N a_i (y_i - \\hat{\\bar{y}} )^2$$ $$\\texttt{V of mean: }\\widehat{V}(\\bar{y}) = \\frac{\\sigma^2_y }{n} * fpc$$\n\nWhere $fpc = \\frac{N-n}{N-1}$ is the finite population correction.\n\n## Accounting for Weights\n\n-   The previous formulas did not account for weights.\n\n-   Weights are factors used to \"reweight/expand\" the sample to make it representative of the population.\n\n-   They can are typically related to the inverse of the probability of selection.\n\n-   Simply said, a weight $w_i=\\frac{1}{n*\\pi_i}$ is a measure of how many observations in the population are represented by observation $i$ in the sample.\n\nBut how do we account for weights in the formulas?\n\n## Summary Statistics with Weights\n\nPopulation: $$\\hat N = \\sum_{i=1}^n w_i$$\n\nNormalized weights $$v_i = \\frac{n w_i}{ \\sum w_i} \\rightarrow E(v_i) = 1$$\n\nMean: $$\\hat{\\mu}_y=\\bar{y} = \\frac{1}{\\hat N}\\sum_{i=1}^n w_i y_i = \\frac{1}{n}\\sum v_i y_i$$\n\n## Variance with Weights\n\nVariances are a bit more complicated. Normally you would consider:\n\n$$Var(\\bar y) = \\frac{1}{n} \\hat \\sigma^2_y =\\frac{1}{n} \\frac{1}{n-1} \\sum_{i=1}^n v_i (y_i - \\bar y)^2$$\n\nHowever, with survey weights you need to consider something else: $$Var(\\bar y) = \\frac{1}{n} \\sum_{i=1}^n v_i^2 (y_i - \\bar y)^2$$\n\nWhich is similar to \"robust\" Standard errors in OLS.\n\n> What about Clusters and Strata?\n\n## How to account for weights in Stata? {.scrollable}\n\nLets use data from the National Health and Nutrition Examination Survey (NHANES) to illustrate how to account for weights in Stata.\n\n::: {.cell .larger execution_count=1}\n``` {.stata .cell-code code-fold=\"false\"}\n frause oaxaca, clear\n** Create Weights <- This will be provided\nsum wt, meanonly\nreplace wt = round(wt/r(min))\ngen wage = exp(lnwage)\n```\n\n::: {.cell-output .cell-output-display}\n```\n<IPython.core.display.HTML object>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n(Excerpt from the Swiss Labor Market Survey 1998)\n(1,647 real changes made)\n(213 missing values generated)\n```\n:::\n:::\n\n\nSummary Statistics:\n\n::: {.cell .larger execution_count=2}\n``` {.stata .cell-code code-fold=\"false\"}\n** unweighted\nsum wage,d\n** weighted\nsum wage [aw=wt],d\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n                            wage\n-------------------------------------------------------------\n      Percentiles      Smallest\n 1%     3.907204       1.661434\n 5%      11.8007       1.873127\n10%      17.4216       2.197802       Obs               1,434\n25%     23.19902       2.442003       Sum of wgt.       1,434\n\n50%     30.08896                      Mean           32.39167\n                        Largest       Std. dev.      16.12498\n75%      38.5662       137.3627\n90%     49.95005       152.6252       Variance       260.0151\n95%     58.71271       164.8352       Skewness       2.486954\n99%     85.47008       192.3077       Kurtosis       18.23702\n\n                            wage\n-------------------------------------------------------------\n      Percentiles      Smallest\n 1%     3.453689       1.661434\n 5%     7.370678       1.873127\n10%     15.83933       2.197802       Obs               1,434\n25%     21.72247       2.442003       Sum of wgt.       2,686\n\n50%     29.48271                      Mean            31.5322\n                        Largest       Std. dev.      16.32811\n75%     38.46154       137.3627\n90%     49.95005       152.6252       Variance       266.6071\n95%     58.11497       164.8352       Skewness       2.081806\n99%     85.47008       192.3077       Kurtosis       14.68647\n```\n:::\n:::\n\n\nAccounting for weights for summary Statistics\n\n::: {.cell .larger execution_count=3}\n``` {.stata .cell-code code-fold=\"false\"}\n** unweighted\nmean wage \n** weighted\nmean wage [pw=wt]\nmean wage [pw=wt], over(female)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMean estimation                          Number of obs = 1,434\n\n--------------------------------------------------------------\n             |       Mean   Std. err.     [95% conf. interval]\n-------------+------------------------------------------------\n        wage |   32.39167   .4258186      31.55637    33.22696\n--------------------------------------------------------------\n\nMean estimation                          Number of obs = 1,434\n\n--------------------------------------------------------------\n             |       Mean   Std. err.     [95% conf. interval]\n-------------+------------------------------------------------\n        wage |    31.5322   .4765835      30.59733    32.46708\n--------------------------------------------------------------\n\nMean estimation                           Number of obs = 1,434\n\n---------------------------------------------------------------\n              |       Mean   Std. err.     [95% conf. interval]\n--------------+------------------------------------------------\nc.wage@female |\n           0  |   33.87649   .6152059      32.66969    35.08329\n           1  |   28.76133    .722173       27.3447    30.17796\n---------------------------------------------------------------\n```\n:::\n:::\n\n\nTables and cross tables\n\n::: {.cell .larger execution_count=4}\n``` {.stata .cell-code code-fold=\"false\"}\n** unweighted\ntab educ female\n\ntab educ female [w=wt]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n           |   sex of respondent\n  years of |      (1=female)\n education |         0          1 |     Total\n-----------+----------------------+----------\n         5 |         6         23 |        29 \n         9 |        47         93 |       140 \n      9.75 |         8         26 |        34 \n        10 |        10         42 |        52 \n      10.5 |       376        447 |       823 \n      11.5 |         7         14 |        21 \n        12 |       111         87 |       198 \n      12.5 |        56         80 |       136 \n        15 |        60         13 |        73 \n      17.5 |        78         63 |       141 \n-----------+----------------------+----------\n     Total |       759        888 |     1,647 \n\n           |   sex of respondent\n  years of |      (1=female)\n education |         0          1 |     Total\n-----------+----------------------+----------\n         5 |        17         45 |        62 \n         9 |       104        181 |       285 \n      9.75 |        14         52 |        66 \n        10 |        22         80 |       102 \n      10.5 |       725        833 |     1,558 \n      11.5 |        19         27 |        46 \n        12 |       201        148 |       349 \n      12.5 |       108        157 |       265 \n        15 |       111         21 |       132 \n      17.5 |       149        111 |       260 \n-----------+----------------------+----------\n     Total |     1,470      1,655 |     3,125 \n```\n:::\n:::\n\n\nBetter approach: `svyset`\n\n::: {.cell .larger execution_count=5}\n``` {.stata .cell-code code-fold=\"false\"}\nwebuse nhanes2f, clear\nsvyset psuid /// Cluster\n       [pweight=finalwgt], /// Survey Weight as Inverse of Prob of Selection\n       strata(stratid)     // Strata Identifier\nmean zinc      \nmean zinc [pw=finalwgt]\nsvy: mean zinc      \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nSampling weights: finalwgt\n             VCE: linearized\n     Single unit: missing\n        Strata 1: stratid\n Sampling unit 1: psuid\n           FPC 1: <zero>\n\nMean estimation                          Number of obs = 9,189\n\n--------------------------------------------------------------\n             |       Mean   Std. err.     [95% conf. interval]\n-------------+------------------------------------------------\n        zinc |   86.51518   .1510744      86.21904    86.81132\n--------------------------------------------------------------\n\nMean estimation                          Number of obs = 9,189\n\n--------------------------------------------------------------\n             |       Mean   Std. err.     [95% conf. interval]\n-------------+------------------------------------------------\n        zinc |   87.18207   .1828747      86.82359    87.54054\n--------------------------------------------------------------\n(running mean on estimation sample)\n\nSurvey: Mean estimation\n\nNumber of strata = 31            Number of obs   =       9,189\nNumber of PSUs   = 62            Population size = 104,176,071\n                                 Design df       =          31\n\n--------------------------------------------------------------\n             |             Linearized\n             |       Mean   std. err.     [95% conf. interval]\n-------------+------------------------------------------------\n        zinc |   87.18207   .4944827      86.17356    88.19057\n--------------------------------------------------------------\n```\n:::\n:::\n\n\n## Testing Significance across 2 groups\n\nConsider two groups with the following characteristics:\n\n| Group | N   | mean | Var   |\n|-------|-----|------|-------|\n| 1     | 100 | 45   | 32.56 |\n| 2     | 150 | 55   | 21.97 |\n\n-   Is the difference in means statistically significant?\n\n-   Test $H_0: \\mu_1 = \\mu_2$ vs $H_1: \\mu_1 \\neq \\mu_2$\n\n$$t = \\frac{\\mu_2 - \\mu_1}{\\sqrt{\\frac{\\sigma_1^2}{n_1} + \\frac{\\sigma_2^2}{n_2}}}\n=\\frac{10}{\\sqrt{\\frac{32.56}{100}+\\frac{21.97}{150}}}=\\frac{10}{.47207} = 14.55453\n$$\n\n-   If $t$ is large enough, we can reject the null hypothesis.\n\n-   But this does not work if you have weights...\n\n## Testing Significance across 2 groups {.scrollable}\n\n-   But you can use OLS to test the difference in means with weights!\n    -   Make sure you use \"robust\" standard errors, or \"pw\" option.\n\n::: {.cell .larger execution_count=6}\n``` {.stata .cell-code code-fold=\"false\"}\n frause oaxaca, clear\n** Create Weights <- This will be provided\nsum wt, meanonly\nreplace wt = round(wt/r(min))\ngen wage = exp(lnwage)\nreg wage i.female [pw=wt],\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Excerpt from the Swiss Labor Market Survey 1998)\n(1,647 real changes made)\n(213 missing values generated)\n(sum of wgt is 2,686)\n\nLinear regression                               Number of obs     =      1,434\n                                                F(1, 1432)        =      29.05\n                                                Prob > F          =     0.0000\n                                                R-squared         =     0.0244\n                                                Root MSE          =     16.133\n\n------------------------------------------------------------------------------\n             |               Robust\n        wage | Coefficient  std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n    1.female |  -5.115156   .9490209    -5.39   0.000    -6.976776   -3.253536\n       _cons |   33.87649   .6154206    55.05   0.000     32.66927    35.08371\n------------------------------------------------------------------------------\n```\n:::\n:::\n\n\n-   you can also use `svy: regress` for complex designs.\n\nsee [here](https://stats.oarc.ucla.edu/stata/faq/how-can-i-do-a-t-test-with-survey-data/) for additional examples\n\n# IO-Tables\n\n## IO-Tables\n\n-   IO tables stand for Input-Output tables. They are a way to represent the production structure of an economy.\n\n-   They provide a Static representation of the Economy\n\n-   Each Row represents the production of a sector, and each column represents the use of that production by other sectors as Inputs.\n\n-   The information it contains represent a snapshot of the economy at a given point in time.\n\n-   It can be used to simulate changes in production, labor demand, and total production in the economy, under specific assumptions (production function)\n\n## \n\n-   Consider a Economy with K=3 sectors: Agriculture, Manufacturing and Services, with a Final consumer agent (households)\n\n-   Each sector (i) produces a good ($X_i$), which is sold to other sectors or the final consumer.\n\n-   $X_{ij}$ is the quantity of goods sector $i$ sells to sector $j$, and $y_i$ the final consumption by households.\n\n-   $X_{ji}$ is also the quantity of goods sector $i$ uses from sector $j$ as inputs.\n\n-   $L_i$ is the amount of labor used by sector $i$.\n\n-   In a simple Economy, (value) Total labor demand is equal to total Household income. $L_a + L_m + L_s = L = y_a + y_m + y_s$\n\n## \n\nThis simple Economy can be represented as follows: $$\n\\begin{aligned}\nX_{11} &+ X_{12} &+ X_{13} &+ Y_{1}  &= X_{1} \\\\\nX_{21} &+ X_{22} &+ X_{23} &+ Y_{2} &= X_{2} \\\\\nX_{31} &+ X_{32} &+ X_{33} &+ Y_{3} &= X_{3} \\\\\nL_1 &+ L_2 &+ L_3 &\\ \\ &= L \n\\end{aligned}\n$$\n\n## \n\nFrom the consumption/inputs Side, we could also write the equations as:\n\n$$\n\\begin{aligned}\nX_{11} &+ X_{21} &+ X_{31} &+ L_{1}  &= X_{1} \\\\\nX_{12} &+ X_{22} &+ X_{32} &+ L_{2} &= X_{2} \\\\\nX_{13} &+ X_{23} &+ X_{33} &+ L_{3} &= X_{3} \\\\\nY_1 &+ Y_2 &+ Y_3 &  &= Y \n\\end{aligned}\n$$\n\nAnd from here we can get the technical coefficients: $$\n\\begin{aligned}\na_{11} X_1 &+ a_{21} X_1 &+ a_{31} X_1 &+ \\lambda_{1} X_1 &= X_1 \\\\\na_{12} X_2 &+ a_{22} X_2 &+ a_{32} X_2 &+ \\lambda_{2} X_2 &= X_2 \\\\\na_{13} X_3 &+ a_{23} X_3 &+ a_{33} X_3 &+ \\lambda_{3} X_3 &= X_3 \\\\\n\\delta_1 Y &+ \\delta_2 Y & + \\delta_3 Y &  &= Y \n\\end{aligned}\n$$\n\nWhere $a_{ij} = \\frac{X_{ij}}{X_j}$ and $\\lambda_i = \\frac{L_i}{X_i}$\n\n$$a_{1i}+a_{2i}+a_{3i}+\\lambda_i = 1 \\ \\& \\ \\delta_1+\\delta_2+\\delta_3 =1$$\n\n## \n\nWith this, we can write the IO table\n\n$$\n\\begin{aligned}\na_{11} X_1 &+ a_{12} X_2 &+ a_{13} X_3  &+ \\delta_1 Y &= X_{1} \\\\\na_{21} X_1 &+ a_{22} X_2 &+ a_{23} X_3  &+ \\delta_2 Y &= X_{2} \\\\\na_{31} X_1 &+ a_{32} X_2 &+ a_{33} X_3  &+ \\delta_3 Y &= X_{3} \\\\\n\\lambda_1 X_1 &+ \\lambda_2 X_2 &+ \\lambda_3 X_3 &\\ \\ &= L \n\\end{aligned} \n$$\n\nOr into Matrix Form $$\n\\begin{pmatrix}\na_{11} & a_{12} & a_{13}  \\\\\na_{21} & a_{22} & a_{23} \\\\\na_{31} & a_{32} & a_{33} \\\\\n\\lambda_1 & \\lambda_2 & \\lambda_3 \n\\end{pmatrix}\n\\begin{pmatrix}\nX_1 \\\\ X_2 \\\\ X_3 \n\\end{pmatrix} + \n\\begin{pmatrix}\nY_1 \\\\ Y_2 \\\\ Y_3 \\\\ 0\n\\end{pmatrix}=\n\\begin{pmatrix}\nX_1 \\\\ X_2 \\\\ X_3 \\\\ L\n\\end{pmatrix}\n$$\n\n## \n\nSolve for Production sectors:\n\n$$\n\\begin{pmatrix}\na_{11} & a_{12} & a_{13}  \\\\\na_{21} & a_{22} & a_{23} \\\\\na_{31} & a_{32} & a_{33} \n\\end{pmatrix}\n\\begin{pmatrix}\nX_1 \\\\ X_2 \\\\ X_3 \n\\end{pmatrix} + \n\\begin{pmatrix}\nY_1 \\\\ Y_2 \\\\ Y_3 \n\\end{pmatrix}=\n\\begin{pmatrix}\nX_1 \\\\ X_2 \\\\ X_3 \n\\end{pmatrix}\n$$\n\n$$\n\\begin{pmatrix}\nY_1 \\\\ Y_2 \\\\ Y_3 \n\\end{pmatrix}=I \\begin{pmatrix} X_1 \\\\ X_2 \\\\ X_3 \\end{pmatrix} -\nA \\begin{pmatrix} X_1 \\\\ X_2 \\\\ X_3 \\end{pmatrix} = (I-A) \\begin{pmatrix} X_1 \\\\ X_2 \\\\ X_3 \\end{pmatrix}\n$$\n\nFinally:\n\n$$\n\\begin{pmatrix} X_1 \\\\ X_2 \\\\ X_3 \\end{pmatrix} = (I-A)^{-1} \\begin{pmatrix} Y_1 \\\\ Y_2 \\\\ Y_3 \\end{pmatrix}\n\\rightarrow \n\\begin{pmatrix} \\Delta X_1 \\\\ \\Delta X_2 \\\\ \\Delta X_3 \\end{pmatrix} = (I-A)^{-1}\n\\begin{pmatrix} \\Delta Y_1 \\\\ \\Delta Y_2 \\\\ \\Delta Y_3 \\end{pmatrix}\n$$\n\n## Example {.scrollable}\n\n-   Consider the following IO table for a simple economy with 3 sectors and a final consumer.\n\n| Sector        | Agriculture | Manufacturing | Services | Final Consumer |\n|---------------|:-----------:|:-------------:|:--------:|:--------------:|\n| Agriculture   |     102     |      103      |   153    |      129       |\n| Manufacturing |     133     |      124      |    77    |       99       |\n| Services      |     71      |      92       |    51    |      165       |\n| Households    |     181     |      114      |    98    |       0        |\n\nS1: What is the total production of each sector?\n\n-   $X_1 = 102 + 103 + 153 + 129 = 487$\n-   $X_2 = 133 + 124 + 77 + 99 = 433$\n-   $X_3 = 71 + 92 + 51 + 165 = 379$\n\nS2: What are the technical coefficients?\n\n| Sector        |   Agriculture    | Manufacturing | Services | Final Consumer |\n|---------------|:----------------:|:-------------:|:--------:|:--------------:|\n| Agriculture   | $a_{11}$ = 0.209 |     0.238     |  0.404   |     0.328      |\n| Manufacturing |      0.273       |     0.286     |  0.203   |     0.252      |\n| Services      |      0.146       |     0.212     |  0.135   |     0.420      |\n| Households    |      0.372       |     0.263     |  0.259   |     0.000      |\n\nThis captures a snapshot of an economy. And could use to simulate changes in production and labor demand.\n\nS3. How much would production change if the final consumer demand for Agriculture increases in 20%?\n\n$$\\Delta X = (I-A)^-1\n\\begin{pmatrix} 0.2 * 129 \\\\ 0 \\\\ 0 \\end{pmatrix} = \n\\begin{pmatrix} 45.54 \\\\ 21.08 \\\\ 12.84 \\end{pmatrix}\n$$\n\nS4: How much would labor demand change if the final consumer demand for Agriculture increases in 20%? $$\\Delta L_i = \\lambda_i * \\Delta X_i$$\n\n$\\Delta L_1 = 0.372 * 45.54 = 16.95 ; \\Delta L_2 =  0.263 * 21.08 = 5.544 ; \\Delta L_3 =  0.259 * 12.84 = 3.326$\n\n## Example - `Stata` {.scrollable}\n\n`mata`: Input Data\n\n::: {.cell .larger execution_count=7}\n``` {.stata .cell-code code-fold=\"false\"}\nmata: x  = (102, 103, 153 \\ 133, 124, 77 \\ 71, 92, 51)\nmata: y  = (129 \\ 99 \\ 165)\nmata: hh = ( 181 , 114 , 98)\n```\n:::\n\n\nEstimate Total Production\n\n::: {.cell .larger execution_count=8}\n``` {.stata .cell-code code-fold=\"false\"}\nmata: tp = colsum(x):+hh ; tp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         1     2     3\n    +-------------------+\n  1 |  487   433   379  |\n    +-------------------+\n```\n:::\n:::\n\n\nEstimate Technical Coefficients\n\n::: {.cell .larger execution_count=9}\n``` {.stata .cell-code code-fold=\"false\"}\n// Technical Coefficients\nmata:ai = x:/tp ; ai\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 1             2             3\n    +-------------------------------------------+\n  1 |  .2094455852   .2378752887   .4036939314  |\n  2 |   .273100616   .2863741339   .2031662269  |\n  3 |  .1457905544   .2124711316   .1345646438  |\n    +-------------------------------------------+\n```\n:::\n:::\n\n\nEstimate Change in Demand: 20% increase in Agriculture\n\n::: {.cell .larger execution_count=10}\n``` {.stata .cell-code code-fold=\"false\"}\n// Technical Coefficients\nmata:dy = y :* (.2 \\ 0 \\ 0); dy\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          1\n    +--------+\n  1 |  25.8  |\n  2 |     0  |\n  3 |     0  |\n    +--------+\n```\n:::\n:::\n\n\nEstimate Change in Production\n\n::: {.cell .larger execution_count=11}\n``` {.stata .cell-code code-fold=\"false\"}\n// Change in Production\nmata:dx = qrinv(I(3)-ai)*dy; dx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 1\n    +---------------+\n  1 |  45.54130481  |\n  2 |  21.08637814  |\n  3 |  12.84872246  |\n    +---------------+\n```\n:::\n:::\n\n\nEstimate Change in Labor Demand\n\n::: {.cell .larger execution_count=12}\n``` {.stata .cell-code code-fold=\"false\"}\nmata:dl = (hh:/tp)':*dx; dl\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 1\n    +---------------+\n  1 |   16.9260291  |\n  2 |  5.551609949  |\n  3 |  3.322360954  |\n    +---------------+\n```\n:::\n:::\n\n\n# SAM: Social Accounting Matrix\n\n## SAM: Social Accounting Matrix\n\n-   SAM can be thought as an upgraded version of IO-tables.\n\n-   They are a way to organize information about the production structure of an economy, but also the distribution of resources.\n\n    -   This it will not only register production of goods and services, but also transfers of resources between sectors and agents.\n\n-   You can also use it as basis for a plausible model of the economy.\n\n    -   Prediction of changes in production, income and distribution.\n\n## Example\n\n|              | Production | Consumption | Accumulation | Totals |\n|--------------|:----------:|:-----------:|:------------:|:------:|\n| Production   |            |     $C$     |     $I$      | $C+I$  |\n| Consumption  |    $Y$     |             |              |  $Y$   |\n| Accumulation |            |     $S$     |              |  $S$   |\n| Totals       |    $Y$     |    $C+S$    |     $I$      |        |\n\n: Closed Economy No GoV SAM\n\n-   Goods/services are Transfered from left to Top-right\n-   Monetary Transfers are from Top-right to left\n\n## Example 2\n\n|           |  S1   |     S2     |   S3    | S4  |   S5    |    Totals     |\n|-----------|:-----:|:----------:|:-------:|:---:|:-------:|:-------------:|\n| S1: Prod  |       |    $C$     |   $G$   | $I$ |   $E$   |   $C+G+I+E$   |\n| S2: HH    |  $Y$  |            |         |     |         |      $Y$      |\n| S3: Gov   |       |    $Tx$    |         |     |         |     $Tx$      |\n| S4: K acc |       |   $S_h$    |  $S_g$  |     |  $S_f$  | $S_h+S_g+S_f$ |\n| S5: RofW  |  $M$  |            |         |     |         |      $M$      |\n| Totals    | $Y+M$ | $C+S_h+Tx$ | $G+S_g$ | $I$ | $E+S_f$ |               |\n\n: Open Economy with GoV SAM\n\nHere $S1$ and $S2$ is what we had in the IO table. Thus, we could further expand the SAM to include more sectors and agents.\n\n## Example 3\n\n|             |    S1    |  S2   |   S3   |   S4    |   S5   |  S6   |   S7   |   S8   |\n|-------------|:--------:|:-----:|:------:|:-------:|:------:|:-----:|:------:|:------:|\n| S1: Act     |          | $Gds$ |        |         |        |       |        |        |\n| S2: Commod  | $IntGds$ |       |        |         |  $C$   |  $G$  |  $I$   |  $E$   |\n| S3: Factors |   $VA$   |       |        |         |        |       |        |  $FE$  |\n| S4: Enter   |          |       | $Prof$ |         |        | $ETr$ |        |        |\n| S5: HH      |          |       | $Wage$ | $DProf$ |        | $Tr$  |        | $REM$  |\n| S6: Gov     |  $ITx$   |       | $FTx$  |  $ETx$  | $DTx$  |       |        | $Tarf$ |\n| S7: K acc   |          |       |        | $RetY$  | $S_h$  | $S_g$ |        | $KTrM$ |\n| S8: RofW    |          |  $M$  |  $FM$  |         | $REMA$ | $TrA$ | $KtrA$ |        |\n\n: MoreDetailed SAM\n\n## Other Extensions\n\n-   SAM also allow you to do further extensions to include more agents (heterogenous)\n    -   Green-Industry\n    -   Informal Sector\n    -   Households by income level\n    -   etc.\n\n# Thats all folks!\n\n## What to get from today?\n\n-   How to use weights in Stata to account for survey design, and how to obtain summary statistics.\n-   How to test differences in means across groups.\n-   How to use IO tables to simulate changes in production and labor demand.\n-   Understand how SAM can be used to represent an Economy\n\n",
    "supporting": [
      "session_1_files\\figure-pdf"
    ],
    "filters": []
  }
}