---
title: "HomeWorks"
format: html
---

This document provides the homework for the each week of the course.  

## Homework 1 {#hw01}

Choose one of the following topics, and create a PDF version of it using Quarto. For this, create a new repository in your GitHub account, this repository should be named `homework_1`, and contain the QMD file that you will use to create the PDF.

For this homework use the following resources

 - Template: [template](hw-material/pdf-template.txt) [html](hw-material/pdf-template.html)
   - Just copy the Heading of this file in your QMD file
 - Bibliography: [reference.bib](hw-material/references.bib)
   - Add this in the same folder as your QMD file
 - All figures, if any, can be saved as PNG or JPG files from the linked pages.
 - Tables, if any, may have to be replicated using `markdown` tables.

Submit the link to your repository, the PDF and QMD files via email.
  
### Topics

- The Impact of Resource Management in StarCraft: A Strategic Analysis 
  My replication
  - [html](hw-material/report1.html) 
  - [pdf](hw-material/report1.pdf)
  - [qmd](hw-material/report1-example.qmd)
- The Strategic Depth of StarCraft and Its Esports Legacy [html](hw-material/report2.html) [pdf](hw-material/report2.pdf)
- The Mathematics of Dungeons and Dragons: A Statistical Adventure [html](hw-material/report3.html) [pdf](hw-material/report3.pdf)
- The Rise of LitRPG: Blending Literature and Gaming [html](hw-material/report4.html) [pdf](hw-material/report4.pdf)
- The Impact of 'The Good Guys' on Modern Fantasy Literature [html](hw-material/report5.html) [pdf](hw-material/report5.pdf)
- Economic Dynamics in Eric Ugland's 'The Good Guys' Series [html](hw-material/report6.html) [pdf](hw-material/report6.pdf)
- The Impact of House Allegiances on Power Dynamics in Westeros [html](hw-material/report7.html) [pdf](hw-material/report7.pdf)

## Homework 2 {#hw02}

- Download country–year panel data on three variables (“indicators”) of your choice from the
World Bank website <https://data.worldbank.org/>, or using their API program (`wbdata`). 
- Once you have the data, clean it up and save a tidy version of it in a Stata file.
- Indicate which countries are ranked highest and lowest in each of the three indicators in the year 2000.
- Write a short report on what you did to obtain the data, how many countries and years you ended up with in the data (after cleannig), and what difficulties you encountered, if any. 

It is not necessary to download the data directly into Stata. You can download the data in CSV format, excel, and then Copy-paste or import it into Stata.

## Homework 3 {#hw03}

- Choose the same 2016/7 season from the `football` dataset as in data exercise (Book) and produce
a different table showing the extent of home team advantage. Compare the results and discuss what you find. 

or

- Using the `wms-management-survey` dataset, pick a country different from Mexico, reproduce all
figures and tables of the Book case study, and compare your results to what was found for Mexico.

## Homework 4 {#hw04}

Nothing here

## Homework 5 {#hw05}

Nothing here

## Homework 6 {#hw06}

q1: Use the `wms-management-survey` dataset and pick a country. (Not two students should pick the same country). Estimate a linear regression with the management quality score (X) and employment (Y). Interpret the slope coefficient, create its 95% CI, and interpret that, too. Explore potential nonlinearities in the patterns of association by `lpoly`. Estimate a regression that can capture those nonlinearities, and carry out a test to see if you can reject that the linear approximation was good enough for the population of firms represented by the data.


## Homework 7 {#hw07}

## Homework 8 {#hw08}

## Homework 9 {#hw09}


Use the stocks-prices dataset that can be found [here](stock_prices.dta). This dataset contains the closing prices for the SP500, Apple, Disney, GameStop, Meta and Nvidia at the end of the month. Using this data, choose one of the companies and reproduce the analysis of the Returns on a company stock and market returns case study (for example SP500 and Apple).

The full case study can be found [here](case_study_returns.pdf). You need to produce the same tables and figures as in the case study, with brief explanations of what you find. No need to use the Daily data, just the Monthly data.


## Homework 10 {#hw10}

Use the data on house prices [here](hhprice_train.dta). This dataset contains the prices of houses in a city, along with many other house charcteristics. You are obtaining 80% of the data to estimate the model. Build a model that you think its best to predict the price of a house. You can use any of the variables in the dataset, and you can create new variables if you think they are useful.

Describe at least 3 different specifications you tried, and which one you choose and why. The one with the best fit on the test data (I have access to) can skip next homework.

See the winner [here](hw10/hw10_ranking.html)

## Homework 11 {#hw11}

## Homework 12 {#hw12}

## Homework 13 {#hw13}
