---
title: "Advance Econometrics: Causal Effects"
---

## Syllabus

Find the syllabus [here-HTML](syllabus.qmd) and [here-PDF](syllabus.pdf) 

All reading materials are available [here](https://github.com/riosavila/madvclass)

[**Introduction**](01Introduction.qmd): Even the longest journey starts somewhere

## Part I: The tools

#### 1. Unveiling the Tapestry of Truth: The Grand Saga of Linear Regression and its Statistical Inference
   
   Linear Regression Model: Statistical Inference and Extensions: [html](02OLS.html) or [pdf](02OLS.pdf)

#### 2. Unleashing the Power of Infinite Flexibility: Exploring the Cosmos of Semi- and Non-Parametric Regression
   
   Semi- and Non-Parametric Regression: How Flexible is Flexible Enough?: [html](03par_spar_npar.html) or [pdf](03par_spar_npar.pdf)

### Homework 1: [html](Homework1.qmd) or [pdf](Homework1.pdf)

#### 3. Beyond the Ordinary: Embarking on the Quest of Conditional Quantile Regressions
   
   Conditional Quantile Regressions: Because No One is Average [html](04cqreg.html) or [pdf](04cqreg.pdf)

#### 4. Ascending the Ladder of Equality: Studying the Mysteries of Unconditional Quantile Regressions
   
   Unconditional Quantile Regressions: When We Care About Everyone [html](05uqreg.html) or [pdf](05uqreg.pdf)

#### 5. Breaking the Chains of Linearity: A Transcendent Expedition into NLS, IRLS, and MLE
   
   NLS, IRLS, and MLE: Going Truly Nonlinear [html](06nlreg.html) or [pdf](06nlreg.pdf)

### Homework 2: [html](Homework2.qmd) or [pdf](Homework2.pdf)

## Part II: The methods

#### 6. Chronicles of Fate: Exploring the Mystical What-Ifs in the Web of Causal Models
   
   Potential outcomes and Causal Models [html](07po_ci.html) or [pdf](07po_ci.pdf)

#### 7. The Mirror's Embrace: Taming Unobservables with the Power of Fixed Effects
   
   Panel Data and Fixed Effects (Many FE) [html](08panel_FE.html) or [pdf](08panel_FE.pdf)

#### 8. The Summoner's Call: Using Instrumental Variables to estimate LATE's
   
   Instrumental Variables [html](09iv.html) or [pdf](09iv.pdf)

#### 9. The Blade of Equivalence: Unleashing the Art of Matching in the Realm of Divergence
   
   Matching and Re-weighting [html](10matching.html) or [pdf](10matching.pdf)   

#### 10. Beyond the Discontinuity Veil: Crossing thresholds to Illuminate Secrets
   
   Regression Discontinuity Design [html](11rdd.html) or [pdf](11rdd.pdf)

#### 11. Twofold Wisdom: Unraveling Truths with the Dual Forces of Differences in Differences
   
   Differences in Differences [pdf](resources/DRDID_CSDID.pdf)      

#### 12. Cosmic Recreations: Forging New Realities through Synthetic Control 
   
   Synthetic Control [html](13SC.html) or [pdf](13SC.pdf)      