{
  "hash": "cc2e23eefda85ab126af397039e91854",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Prediction Setup\"\nsubtitle: \"How far should we go?\"\nauthor: \n  - name: Fernando Rios-Avila\n    affiliation: Levy Economics Institute  \ndate: last-modified\ndate-format: long\nformat:\n  revealjs:\n    theme: [ clean2.scss]\n    slide-number: true\n    footer: \"*Rios-Avila and Cia*\"\n    width:  1200\n    height: 700\njupyter: nbstata    \nexecute: \n  cache: true\n  freeze: auto  \n---\n\n\n## Motivation\n\n- Imagine you want to sell your car soon and need to predict its price. You have data on similar used cars, and several regression models could help estimate its value now and in a year. How do you choose the best model? \n \n- Or, take an ice cream shop—using past sales and temperature data, you want to predict sales for the coming days. What factors should you consider to ensure your prediction is as accurate as possible?\n \n## Prediction Basics\n\n- We start with original data (what we have) $\\rightarrow$ to build a model\n- There is Live data (data we do not have yet)\n  \n- The Target variable $Y$ (=dependent variable, response, outcome)\n- Predictor variables $X$ (= inputs, covariates, features, independent variables)\n\n- The goal is to predict value of $Y$ for target observation $j$ in live data\n  - Actual value for $Y_j$ unknown\n  - but value for $X_j$ known\n  - Need predicted value of $Y$ for each target observation $j$\n\n## CS: Price cars\n\n- You want to sell your car through online advertising\n- Target is continuous (in dollars)\n- Features are continuous or categorical\n- The business question:\n  - What price should you put into the ad?\n\n##  CS: Price apartments \n\n- You are planning to run an AirBnB business\n  - Maybe several rooms\n- Target is continuous (in dollars)\n- Features are varied from text to binary\n- The business question:\n  - How should you price apartments/houses?\n\n## CS: Predict company's exit from business \n\n- You have a consulting company\n- Predict which firms will go out of business (exit) from a pool of partners\n- Target is binary: exit / stay\n- Features of financial and management info\n- Business decision:\n  - Which firms to give loan to?\n\n## Predictive Analysis: what is new?\n\n- Most of econometrics focused on finding relationships between $X$ and $Y$\n  - What is the relationship like (+/-, linear, etc.)\n  - Is it a robust relationship – true in the population /general pattern? (causal?)\n- Now, we use $x_1, x_2, \\dots$ to predict $y$: $\\hat{y}_j = \\hat{f}(x_j)$\n- How is this different?\n  \n:::{.fragment}  \n  - We care less about\n    - Individual coefficient values, multicollinearity\n  - We still care about the stability of our results.\n  - Should we care about causality?\n    - Not so much, we care more about making the best prediction.\n:::\n\n# Different types of prediction\n\n## What are we predicting?\n\n- $Y$ is quantitative (e.g price)\n  - Quantitative prediction\n  - \"Regression\" problem\n- $Y$ is binary (e.g. Default or nor)\n  - Probability prediction\n  - Classification problem\n  - Broadly: $Y$ takes values in a finite set of (unordered) classes (survived/died, sold/not sold, car model)\n- Time series prediction (Forecasting). Make predictions about the future based on historical and current data.\n\n## What is Different?\n\n- Feature engineering (variable selection) including variable selection, coding and functional form\n- Model building and prediction\n  - Decision regarding model complexity and estimation\n    - Remember splines, polynomials\n  - Machine learning methods\n    - Automated model selection under some conditions\n- Model evaluation and selection\n  - Compare models based on some measure of fit\n- Key idea: Focus on systematically combine estimation and model selection\n\n## Supervised Machine Learning Technique: Regression\n\n- Linear regression produces a predicted value for the dependent variable.\n  - **Predictions**: are the expected value of $y$ if we know $x$.\n- Linear regression with $y, x_1, x_2, etc.,$, is a model for the conditional expected value of $y$, which provide us with $\\beta's$.\n- We need estimated coefficients $(\\hat{\\beta})$ and actual $x$ values $(x_j)$ to predict an actual value $\\hat{y}$\n  \n$$\\begin{aligned}\ny^E &= \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\dots \\\\\n\\hat{y}_j &= \\hat{\\beta}_0 + \\hat{\\beta}_1 x_{1j} + \\hat{\\beta}_2 x_{2j} + \\dots\n\\end{aligned}\n$$\n\n## The Prediction Error\n\n- The Regression model can produce a Predicted value $\\hat{y}_j$ for target observation $j$\n- but, actual value $y_j$ is not known (that is why we are predicting)\n- Thus, there will be a prediction error\n\n$$e_j = \\hat{y}_j - y_j\n$$\n\n- Error = actual value - predicted value\n\n## The Prediction Error\n\n- The **ideal** prediction error, is zero: our predicted value is right on target.\n- The prediction error is defined by the direction of miss and size.\n- Direction of miss:\n  - Positive if we overpredict the value: we predict a higher value than actual value.\n  - Negative if we underpredict the value: our prediction is too low.\n  - Degree of wrongness depends on the decision problem.\n- Size:\n  - Larger in absolute value the further away our prediction is from the actual value.\n  - It is smaller the closer we are.\n  - It is always better to have a prediction with as small an error as possible.\n\n## Decomposing the prediction error\n\nAssume the best model for $Y$ is $Y = f(X,Z,XZ) + \\epsilon$ \n\n- The prediction error can be decomposed into three parts:\n  1. **estimation error**: Difference between $f(X,Z,XZ)$ and $\\hat f(X,Z,XZ)$\n  2. **model error**: If we using $f(X,Z)$, it would be the Difference between $f(X,Z)$ and $f(X,Z,XZ)$.\n  3. **genuine error**: error even if have the best possible model. $\\epsilon$\n\n## Interval prediction for quantitative target variables\n\n- One advantage of regressions - it's easy quantify uncertainty of prediction\n  - This can be used to obtain **Interval predictions**\n- Interval predictions quantify 2-out-of-3 sources of prediction uncertainty: estimation error and genuine (or irreducible) error.\n- They do not include the third source, model uncertainty! (Bayesian methods can help with this)\n- The 95% prediction interval (PI) tells where to expect the actual value for the target observation.\n- The PI for linear regression requires homoskedasticity. (but could be relaxed)\n\n# The Loss function\nChoosing the best \n\n## Loss Functions\n\n- We use a Loss function to quantify the **cost** of prediction error\n  - It attaches a value to the prediction error, specifying how **bad** it is\n  - Thus, Loss function determines best predictor\n- Ideally, it is derived from decision problem, \n  - How much more costly is to overpredict than underpredict? (price is right!)\n  - The shape and functional form could depent on the decision problem\n- In practice, highly crafted loss functions are rare (Machine learning, Neural Networks, Etc), so we use common ones\n- Loss functions could be used to both estimate, but also to **evaluate/compare**  models\n\n## Loss Functions\n\n- The most important Loss functions have the following characteristics:\n  - **Symmetry**: losses due to errors in opposing direction are similar \n    - **Asymmetric loss**: overprediction is more costly than underprediction\n  - **Convexity**: Twice as large errors generate more than twice as large losses. (We penalize large errors more than small ones)\n    - **Linear loss**: Errors are penalized proportionally to their size\n\n## Loss Functions of Various Shapes\n\n::: {#2d075875 .cell execution_count=2}\n``` {.stata .cell-code code-fold=\"true\"}\nqui {\nclear\nset scheme white2\ncolor_style tableau\nset obs 301\nrange r -5 5 \ngen ll = r^2\ngen ll2 = 2*abs(r)\ngen ll3 = 1.5*r^2*(r>0)+0.5*r^2*(r<0)\ndrop if ll>30 | ll2>30 | ll3>30\nline ll ll2 ll3 r, lw(1 1 1) ///\n    legend(order(1 \"Symetric-Convex\" 2 \"Symetric-Linear\" 3 \"Asymetric-Convex\") )\n}\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style>div.jp-Notebook .datagrid-container {min-height: 448px; }</style>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](week10_files/figure-revealjs/cell-2-output-2.png){fig-align='center'}\n:::\n:::\n\n\n## Examples 1 – used cars\n\n- The loss function for predicting the value of our used car depends on how we value money and how we value how much time it takes to sell our car (value of your car).\n- A too low prediction may lead to selling our car cheap but fast;\n- A too high prediction may make us wait a long time and, possibly, revising the sales price downwards before selling our car.\n- What kind of loss function would make sense?\n\n## Examples 2 - creditors\n\n- Creditors decide whether to issue a loan only to potential debtors that are predicted to pay it back with high likelihood.\n- Two kinds of errors are possible:\n  - debtors that would pay back their loan don't get a loan\n  - debtors that would not pay back their loan get one nevertheless.\n- The costs of the first error are due to missed business opportunity; the costs of the second error are due to direct loss of money.\n- These losses may be quantified in relatively straightforward ways.\n- What kind of loss function would make sense?\n\n## Some common loss functions\n\nSquared loss function:\n  \n$$L(e_j) = e^2_j = (\\hat{y}_j - y_j)^2\n$$\n\n- The most widely used loss function\n- Symmetric: Losses due to errors in opposing direction are same\n- Convex: Twice as large errors generate more than twice (4x) as large losses\n\n## Some common loss functions\n\nAbsolute loss function:\n  \n$$L(e_j) = e^2_j = Abs(\\hat{y}_j - y_j)\n$$\n\n- Used for Median regression (Quantile regression)\n- Symmetric: Losses due to errors in opposing direction are same\n- Linear: Twice as large errors generate twice as large losses\n\n- Quantile Regressions use Asymetric loss functions\n\n## Mean Squared Error: MSE \n\n- The most common way to quantify and aggregate the loss function is using the Mean Squared Error (MSE) \n- Squared loss $\\rightarrow$ Mean Squared Error (MSE)\n\n$$\\begin{align*}\n\\text{MSE} &= \\frac{1}{K} \\sum_{k=1}^K (\\hat{y}_k - y_k)^2 \\\\\n\\text{RMSE} &= \\sqrt{\\text{MSE}} = \\sqrt{\\frac{1}{K} \\sum_{k=1}^K (\\hat{y}_k - y_k)^2}\n\\end{align*}\n$$\n\n- Using this function typically implies we are interested in the Mean as the best predictor\n\n## MSE decomposition : Bias and Variance\n\n- The MSE can be decomposed into two parts: **Bias** and **Variance**\n$$\\begin{align*}\nMSE &= \\frac{1}{J}\\sum_{j=1}^J (\\hat{y}_j - y_j)^2 \\\\\n &= \\left(\\frac{1}{J}\\sum_{j=1}^J (\\hat{y}_j - y_j)\\right)^2 + \\frac{1}{J}\\sum_{j=1}^J (\\hat y_j - \\bar{\\hat y})^2 \\\\\n &= \\text{Bias}^2 + \\text{PredictionVariance}\n\\end{align*}\n$$\n\n- The bias of a prediction is the average of its prediction error.\n  - How far off is the average prediction from the actual value?\n- The variance of a prediction describes shows how it varies around its average.\n\n## MSE decomposition : Bias and Variance\n\n$$\\begin{align*}\n\\text{MSE} &= \\frac{1}{K} \\sum_{k=1}^K (\\hat{y}_k - y_k)^2 \\\\\n         &= \\left(\\frac{1}{K} \\sum_{k=1}^K (\\hat{y}_k - \\bar{y})\\right)^2 + \\frac{1}{K} \\sum_{k=1}^K (y_k - \\bar{y})^2 \\\\\n         &= \\text{Bias}^2 + \\text{PredictionVariance}\n\\end{align*}$$\n\n- OLS is unbiased. Some other methods will allow for some bias in return for lower variance.\n\n## Case study: used cars data\n\n- Suppose you want to sell your car of a certain make, type, year, miles, condition and other features.\n- The prediction analysis helps uncover the average advertised price of cars with these characteristics\n- That helps decide what price you may want to put on your ad.\n\n## Case study: used cars data\n\n- Scraped from a website\n- Year of make (age), Odometer (miles)\n- Tech specifications such as fuel and drive\n- Dealer or private seller\n\n## Case study: Loss function\n\n- The loss function for predicting the value of our used car depends on how we value money and how we value how much time it takes to sell our car.\n- A too low prediction may lead to selling our car cheap but fast;\n- A too high prediction may make us wait a long time and, possibly, revising the sales price downwards before selling our car.\n- Symmetric\n- Sensitive to big deviations\n- RMSE and OLS\n\n## Case study - used cars: features\n\n- Odometer, measuring miles the car traveled (Continuous, linear)\n- More specific type of the car: LE, XLE, SE (missing in about 30% of the observations). (Factor – set of dummies , incl N/A)\n- Good condition, excellent condition or it is like new (missing for about one third of the ads). (Factor – set of dummies, incl N/A)\n- Car's engine has 6 cylinders (20% of ads say this; 43% says 4 cylinders, and the rest has no information on this). (Binary for 6 cylinders)\n\n## Case study: models by hand\n\n- Model 1: age, age squared\n- Model 2: age, age squared, odometer, odometer squared\n- Model 3: age, age squared, odometer, odometer squared, LE, excellent condition, good condition, dealer\n- Model 4: age, age squared, odometer, odometer squared, LE, excellent condition, good condition, dealer, LE, XLE, cylinder\n- Model 5: same as Model 4 but with all variables interacted with age (won't show in next table)\n\n## Case study: Car price model results\n\n```\n(1)   (2)   (3)   (4)\nVariables Model 1 Model 2 Model 3 Model 4\nage     -1,530.09 -1,149.22 -873.47 -836.64\nagesq    35.05   27.65   18.21   17.63\nodometer           -303.84 -779.90 -788.70\nodometersq                 18.81   19.20\nLE                         28.11  -20.48\nXLE                                301.69\nSE                                1,338.79\ncond_likenew                       558.67\ncond_excellent                     176.49  190.40\ncond_good                          293.36  321.56\ncylind6                           -370.27\ndealer                            572.98  822.65\nConstant 18,365.45 18,860.20 19,431.89 18,963.35\n```\n\n## Case study: Results\n\n- When doing prediction, coefficients are less important.\n- But we shall use them for sanity check: age negative, convex (flattens out)\n- SE may not be even displayed. It is helpful for model selection, but only along with other measures\n- and values of the predictor variables for our car: age = 10 (years), odometer= 12 (10 thousand miles), type= LE, excellent condition=1.\n- A point prediction, Model 3: age: -873.47, age squared=18.21, odometer -799.90, odometer sq = 18.81, LE=28.11, cond excellent: 176.49+ C=19.431.89\n- Predicted is price is 6073.\n\n## Case study: Prediction Interval\n\n- Calculating prediction intervals for the baseline models\n- Very wide interval despite high R2\n- Prediction is hard!\n- Even with a good model, you'll make plenty of errors\n- Should be aware\n- Let your clients know in advance...\n\n## Case study: Prediction Interval\n\nBased on the third model, we have a point prediction of $6073$\nHave a 80% prediction intervals (PI) – Ads for cars just like ours may ask a price ranging from $4,317$ to $7,829$ with a 80% chance.\n\n| Model 1 | Model 3 |\n|---------|---------|\n| Point prediction 6,569 | 6,073 |\n| Prediction Interval (80%) [4,296-8,843] | [4,317-7,829] |\n| Prediction Interval (95%) [3,085-10,053] | [3,382-8,763] |\n\nNote: Chicago cars. Prices in dollars.\nSource: used-cars dataset.\n\n## Model selection\n\n## Data for prediction\n\n- We have a dataset\n- We wanna make some prediction\n\n## Model selection\n\nModel selection is finding the best fit while avoiding overfitting and aiming for high external validity\n\n## External validity, avoiding overfitting and model selection\n\n- Have a dataset and a target variable. Compare various models of prediction.\n- How to choose a model?\n- Pick a model that can predict well....\n- Best prediction - best model that would produce the smallest prediction error.\n- Context of squared loss function $\\rightarrow$ finding the regression that would produce the smallest RMSE for the target observations.\n- Pick a model that can predict well on the live data\n\n## Underfit, overfit\n\n- Comparing two models (model 1 and model 2)\n- Model 1 can give a worse fit in the live data than model 2 in two ways.\n  - Model 1 may give a worse fit both in the original data and the live data. In this case, we say that model 1 underfits the original data.\n    - Simple: we should build a better model.\n  - Model 1 may actually give a better fit in the original, but a worse fit in the live data. In this case, we say that model 1 overfits the original data.\n\n## Overfitting\n\n- Overfitting is a key aspect of external validity\n- finding a model that fits the data better than alternative models\n- but makes worse actual prediction.\n- Thus, the problem of overfitting the original data is best split into two problems:\n  - fitting patterns in the original data that are not there in the population, or general pattern, it represents;\n  - fitting patterns in the world of the original data that will not be there in the world of the live data.\n\n## Reason for overfitting\n\n- The typical reason for overfitting is fitting a model that is too complex on the dataset.\n- Complexity: number of estimated coefficients\n- Often: fitting a model with too many predictor variables.\n- Including too many variables from the dataset that do not really add to the predictive power of the regression,\n- often because they are strongly correlated with other predictor variables.\n- Specifying too many interactions,\n- Too detailed nonlinear patterns\n  - as piecewise linear splines with many knots\n  - polynomials of high degree.\n\n## Increasing model complexity\n\n- As we increase model complexity\n  - Such as number of features (variables)\n  - By adding interactions, etc.\n- We will see\n  - RMSE within dataset to fall monotonously\n  - RMSE for target observations (ie. not in our dataset) to fall and then rise as we overfit\n- example to come in class 2\n\n## Finding the best model by best fit and penalty: The BIC\n\n- Approach 1: Indirectly\n- Estimate it by an adjustment\n- Use a method based on some distributional assumptions\n- Need to pick an evaluation criterion\n- =In-sample evaluation with penalty\n- Specify and estimate model using all data\n- Use a measure of fit that helps avoid overfitting\n  - Such as\n    - adjusted $R^2$\n    - BIC = Bayesian Information Criterion, or Schwarz criterion\n\n## Indirect evaluation criteria\n\n- Main methods: AIC, BIC and adjusted $R^2$\n- Advantage: easy to compute\n- Disadvantage: assumptions\n- Adjusted $R^2$ – just add a penalty for having many RHS vars\n  - corrects with $(n - 1)/(n - p - 1)$\n- Akaike Information Criterion\n  - AIC = $-2 \\times \\ln(\\text{likelihood}) + 2 \\times k$\n- Schwarz – Bayesian Information Criterion\n  - BIC = $-2 \\times \\ln(\\text{likelihood}) + \\ln(N) \\times k$\n- Both quantities that take the log likelihood and apply a penalty for the number of parameters being estimated.Both are based on information loss theory from the fifties.\n- BIC puts heavier penalty on models with many RHS variables, than AIC.\n\n## Model fit evaluation\n\n- Use a good measure of fit to compare models.\n- Don't\n  - Don't use MSE or R-squared (the two very closely related).\n  - They choose best fit in data and don't care about overfitting.\n- In practice, use BIC.\n- BIC good approximation of what more sophisticated methods would pick. Or even more conservative...\n- That introduces a \"penalty term\"\n- More predictor variables leads to worse value\n- Even more so in large samples.\n\n## Finding the best model by training and test samples\n\n- Approach Nr.2: Directly\n- Estimate it using a test (validation) set approach.\n- Needs cutting the dataset into training and test sample\n- No assumption\n- Need to pick evaluation criterion (loss function) = RMSE (root mean squared error)\n- Estimate the model in part of the data (say, 80%).\n  - Training sample\n- Evaluate predictive performance on the rest of the data.\n  - Test sample\n- Avoid overfitting in training data by evaluating on test data.\n\n## Training and Test Samples\n\n- Creating two sub-samples\n- Randomly! (ie. not 1—80 and 81—100)\n- Randomly generate an ID, sort and create two sub-samples.\n- Training sample 80%\n  - Regressions will be on run on this sample\n  - Coefficients estimated\n- Test (validation) sample 20%\n  - Using estimated coefficients, we predict values for flats in the validation sample\n  - Calculate residual, RMSE in the test sample\n- RMSE rather than MSE – smaller numbers....\n\n## 5-fold cross-validation\n\n- Split sample $k=5$ times to train and test\n- For each folds:\n  - Estimate model on training.\n  - Get coefficients.\n  - Use them to estimate on Test\n  - Calculate test MSE\n- Average and take Sqrt\n- Repeat for models\n- Pick model w lowest avg RMSE\n\n## BIC vs test RMSE\n\n- In our experience, in practice, BIC is the best indirect criterion – closest to test sample.\n- The advantage of BIC is that it needs no sample splitting which may be a problem in small samples.\n- The advantage of test MSE is that it makes no assumption.\n- BIC is a good first run, quick, is often not very wrong.\n- Ultimately, you want to do a test MSE.\n\n## Case study: Model selection\n\n- We have the ingredients, we need to pick a model.\n- This process involves variable selection and a decision rule of choosing the model based on some loss function.\n- BIC on the actual data\n- Test-sample RMSE\n- Cross-validated (CV) RMSE\n- If enough data / computer power, use CV RMSE\n- With larger dataset, overfit becomes less of an issue.\n\n## Case study: Model selection\n\n| Model | N vars | N coeff | R-squared | RMSE | BIC |\n|-------|---------|---------|-----------|------|-----|\n| 1 Model 1 | 3 | 0.85 | 1,755 | 5,018 |\n| 2 Model 2 | 5 | 0.90 | 1,433 | 4,910 |\n| 3 Model 3 | 9 | 0.91 | 1,322 | 4,893 |\n| 4 Model 4 | 12 | 0.92 | 1,273 | 4,894 |\n| 5 Model 5 | 22 | 0.92 | 1,239 | 4,935 |\n\nNote: In sample values. Model 1: age, age squared, Model 2= Model 1 +odometer, odometer squared, Model 3= Model2 + SE, excellent condition, good condition, dealer, Model 4= Model 3 + LE, XLE, like new condition, 6cylinder, Model 5 = Model 4 + many interactions.\nSource: used-cars dataset.\n\n## Case study: Model selection\n\n- Cross-validate using 4-fold cross validation.\n- Run the regression on 3/4 of the sample, predicting on the remaining 1/4 of the sample, get RMSE on test sample.\n- We then average out RMSE values over the 4 test samples\n\n| Fold No. | Model 1 | Model 2 | Model 3 | Model 4 | Model 5 |\n|----------|---------|---------|---------|---------|---------|\n| 1 Fold1  | 1,734   | 1,428   | 1,331   | 1,395   | 1,391   |\n| 2 Fold2  | 2,010   | 1,781   | 1,692   | 1,638   | 1,693   |\n| 3 Fold3  | 1,465   | 1,251   | 1,256   | 1,253   | 1,436   |\n| 4 Fold4  | 1,823   | 1,325   | 1,250   | 1,246   | 1,307   |\n| 5 Average| 1,769   | 1,460   | 1,394   | 1,392   | 1,464   |\n\nSource: used-cars dataset.\n\n## Case study: Model selection\n\n- Model 3 has lowest BIC, lowest average RMSE on test samples. Model 4 is close.\n- Interestingly, both approaches suggests that Model 3 is the one that has the best prediction properties\n- Small sample, simple model.\n\n## External validity and stable patterns\n\n- BIC, Training-test, k-fold cross-validation...\n- All very nice\n- But, in the end, they all use the information in the data.\n- How would things look for the target observation(s)?\n- The issue of stationarity – how our data is related to other datasets we may use our model\n- We may have some ideas\n- We may use non-random test samples that may mimic the difference in our data and the target observations\n- In the end we can't know but need to think about it.\n- Plus be aware, that some difference is likely, so your model fit in an outside data source is likely to be worse...\n\n## External validity and stable patterns\n\n- Most predictions will be on future data\n- High external validity requires that the environment is stationary.\n- Stationarity means that the way variables are distributed remains the same over time.\n- Here that distribution is to be understood in a general way: the joint distribution of predictor variables and target variable are required to remain the same throughout the time covered in the data and the time of the forecast.\n- Stationarity ensures that the relationship between predictors and the target variable is the same in the data and the forecasted future.\n- If the relationship breaks down whatever we establish in our data won't be true in the future, leading to wrong forecasts.\n\n## External validity and stable patterns\n\n- External validity and stable patterns - Very broad concept\n- It's about representativeness of actual data $\\rightarrow$ to live data\n- Often hard to know.\n- Remember hotels (other dates, other cities).\n- Domain knowledge can help.\n- Study if patterns were stable in the past / other locations were stable can help.\n\n## Algorithms\n\n## Machine Learning and the Role of Algorithms\n\n- Predictive analytics is often used for data analysis whose goal is prediction. But a more popular, and related, term is machine learning.\n- Machine learning is an umbrella concept for methods that use algorithms to find patterns in data and use them for prediction purposes.\n- An algorithm is a set of rules and steps that defines how to generate an output (predicted values) using various inputs (variables, observations in the original data).\n- A formula is an example of an algorithm – one that can be formulated in terms of an equation.\n- OLS formula for estimating the coefficients of a linear regression is an algorithm.\n\n## Machine Learning Algorithms\n\n- Machine learning is about algorithms, machines and learning\n- Algorithms specify each and every step to follow in a clear way.\n- Not all algorithms can be translated into a formula.\n  - The bootstrap estimation of a standard error (Chapter 5, Section 5.6) is an example.\n  - K-fold cross-validation.\n- Heavy use of machines = computers. Steps of algorithm translated into computer code and make the computer follow those steps. Fast.\n- Learning - learn something from the data with data and an algorithms.\n  - Predicted value of $y =?$ If combine $x$ variables using a particular model.\n  - learning which model is best for predicting $y$ as well as what that predicted value is.\n\n## What is, machine learning?\n\n- Many definitions, discussions.\n- Here: Machine learning is an approach to predictive data analysis – achieving the best possible prediction from available data.\n- Consequence 1: understanding the patterns of associations between $y$ and $x$ is of secondary importance.\n- We need stable patterns for good prediction in live data, but that is it.\n- The machine learning attitude - a preference for evaluating methods based on data as opposed to abstract principles.\n- Original data to live data\n- Not a general rule or philosophy\n- Machine learning broadly: all prediction models including OLS\n- Machine learning narrowly: prediction models with no formula, ie not OLS\n\n## Main takeaways\n\n- Prediction uses the original data with $y$ and $x$ to predict the value of $y$ for observations in the live data, in which $x$ is observed but $y$ is not\n- Prediction uses a model that describes the patterns of association between $y$ and $x$ in the original data\n- Cross-validation can help find the best model in the population, or general pattern, represented by the original data\n- Stability of the patterns of association is needed for a prediction with high external validity\n\n",
    "supporting": [
      "week10_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}